#!/usr/bin/env bash
set -euo pipefail

# Launch covariate-adjusted randomise jobs generated by MakeCovariateRandomiseModels.py.

usage() {
    cat <<'USAGE'
Usage: code/run_covariate_randomise.sh [options]

Discover generated covariate randomise model folders and launch each job with
bounded concurrency.

Options:
  --models LIST             Comma-separated model labels (default: fdmean-blink,fdmean-pupil)
                            Labels may be written with or without model-/cov- prefixes.
  --max-jobs N              Concurrent randomise processes (default: RANDOMISE_MAX_JOBS or 32)
  --n-perm N                Permutations per job (default: N_PERM or 5000)
  --cluster-threshold VALUE Cluster-forming t threshold (default: CLUSTER_THRESHOLD or 3.1)
  --tfce                    Also calculate TFCE inference (default: off)
  --dry-run                 Print and validate the launch plan only
  --help                    Show this message
USAGE
}

models_csv="${COVARIATE_RANDOMISE_MODELS:-fdmean-blink,fdmean-pupil}"
maxjobs="${RANDOMISE_MAX_JOBS:-32}"
nperm="${N_PERM:-5000}"
cluster_threshold="${CLUSTER_THRESHOLD:-3.1}"
tfce=0
dryrun=0

while (($#)); do
    case "$1" in
        --models) models_csv="${2:-}"; shift 2 ;;
        --max-jobs) maxjobs="${2:-}"; shift 2 ;;
        --n-perm) nperm="${2:-}"; shift 2 ;;
        --cluster-threshold) cluster_threshold="${2:-}"; shift 2 ;;
        --tfce) tfce=1; shift ;;
        --dry-run|--render-only) dryrun=1; shift ;;
        --help|-h) usage; exit 0 ;;
        *) echo "ERROR: Unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

[[ -n "$models_csv" ]] || { echo "ERROR: --models cannot be empty." >&2; exit 1; }
[[ "$maxjobs" =~ ^[1-9][0-9]*$ ]] || { echo "ERROR: --max-jobs must be positive." >&2; exit 1; }
[[ "$nperm" =~ ^[1-9][0-9]*$ ]] || { echo "ERROR: --n-perm must be positive." >&2; exit 1; }
[[ "$cluster_threshold" =~ ^[0-9]+([.][0-9]+)?$ ]] || {
    echo "ERROR: --cluster-threshold must be nonnegative numeric value." >&2
    exit 1
}

scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
maindir="$(dirname "$scriptdir")"
derivdir="${DERIVATIVES_ROOT:-${maindir}/derivatives}"
fsldir="${FSL_OUTPUT_DIR:-${derivdir}/fsl}"

expected_outputs_exist() {
    local prefix="$1"
    [[ -f "${prefix}_tstat1.nii.gz" ]] || return 1
    [[ -f "${prefix}_tstat2.nii.gz" ]] || return 1
    [[ -f "${prefix}_clustere_corrp_tstat1.nii.gz" ]] || return 1
    [[ -f "${prefix}_clustere_corrp_tstat2.nii.gz" ]] || return 1
    if [[ "$tfce" == 1 ]]; then
        [[ -f "${prefix}_tfce_corrp_tstat1.nii.gz" ]] || return 1
        [[ -f "${prefix}_tfce_corrp_tstat2.nii.gz" ]] || return 1
    fi
}

job_complete() {
    local prefix="$1"
    [[ -f "${prefix}.complete" ]] && expected_outputs_exist "$prefix"
}

declare -a model_labels=()
IFS=',' read -r -a requested_models <<<"$models_csv"
for model in "${requested_models[@]}"; do
    model="${model//[[:space:]]/}"
    [[ -n "$model" ]] || continue
    [[ "$model" == model-* ]] && model="${model#model-}"
    [[ "$model" == cov-* ]] || model="cov-${model}"
    [[ "$model" =~ ^cov-[a-z0-9][a-z0-9-]*$ ]] || {
        echo "ERROR: Invalid model label: $model" >&2
        exit 1
    }
    model_labels+=("$model")
done
[[ "${#model_labels[@]}" -gt 0 ]] || { echo "ERROR: No valid models requested." >&2; exit 1; }

plan="$(mktemp "${TMPDIR:-/tmp}/r21_covariate_randomise_plan.XXXXXX")"
cleanup() {
    rm -f "$plan"
}
trap cleanup EXIT

missing_count=0
complete_count=0
stale_complete_count=0
job_count=0
manifest_count=0

for model in "${model_labels[@]}"; do
    while IFS= read -r job_file; do
        [[ -n "$job_file" ]] || continue
        manifest_count=$((manifest_count + 1))
        model_dir="$(dirname "$job_file")"
        component_dir="$(cd "${model_dir}/../.." >/dev/null 2>&1 && pwd)"
        dr_dir="$(cd "${component_dir}/../.." >/dev/null 2>&1 && pwd)"
        mask="${dr_dir}/mask.nii.gz"
        if [[ ! -f "$mask" ]]; then
            echo "ERROR: Missing mask for ${job_file}: ${mask}" >&2
            missing_count=$((missing_count + 1))
        fi
        while IFS=$'\t' read -r contrast network group_input design_mat design_con design_grp output_prefix; do
            [[ "$contrast" == "contrast" ]] && continue
            [[ -n "$contrast" ]] || continue
            job_count=$((job_count + 1))
            for required in "$group_input" "$design_mat" "$design_con"; do
                if [[ ! -f "$required" ]]; then
                    echo "ERROR: Missing input for ${model} ${contrast} ${network}: ${required}" >&2
                    missing_count=$((missing_count + 1))
                fi
            done
            if job_complete "$output_prefix"; then
                complete_count=$((complete_count + 1))
            elif [[ -f "${output_prefix}.complete" ]]; then
                stale_complete_count=$((stale_complete_count + 1))
                echo "WARN: Ignoring stale complete marker with missing outputs: ${output_prefix}.complete" >&2
            fi
            printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
                "$model" "$contrast" "$network" "$mask" "$group_input" "$design_mat" "$design_con" "$output_prefix" >>"$plan"
        done <"$job_file"
    done < <(find "$fsldir" -path "*/covariate-models/model-${model}/randomise_jobs.tsv" -type f | sort)
done

if [[ "$manifest_count" -eq 0 ]]; then
    echo "ERROR: No covariate randomise job manifests found under: $fsldir" >&2
    echo "Run MakeCovariateRandomiseModels.py first, for example:" >&2
    echo "  python3 code/MakeCovariateRandomiseModels.py --covariates fdmean,blink --overwrite" >&2
    echo "  python3 code/MakeCovariateRandomiseModels.py --covariates fdmean,pupil --overwrite" >&2
    exit 1
fi

printf 'FSL output root: %s\n' "$fsldir" >&2
printf 'Models: %s\n' "$(IFS=','; echo "${model_labels[*]}")" >&2
printf 'Model manifests: %d\n' "$manifest_count" >&2
printf 'Randomise jobs: %d; already complete: %d; stale complete markers: %d; pending: %d; maximum concurrent: %d\n' \
    "$job_count" "$complete_count" "$stale_complete_count" "$((job_count - complete_count))" "$maxjobs" >&2
printf 'Permutations: %d; TFCE: %s; cluster threshold: %s\n' \
    "$nperm" "$([[ "$tfce" == 1 ]] && echo yes || echo no)" "$cluster_threshold" >&2

if [[ "$missing_count" -gt 0 ]]; then
    echo "ERROR: Preflight found ${missing_count} missing required input(s)." >&2
    exit 1
fi

if [[ "$dryrun" == 1 ]]; then
    echo "Dry run only; no randomise jobs launched." >&2
    awk -F $'\t' '{print "  " $1 " " $2 " " $3 " -> " $8}' "$plan" >&2
    exit 0
fi

command -v randomise >/dev/null 2>&1 || { echo "ERROR: randomise is not on PATH." >&2; exit 1; }
mkdir -p "${fsldir}/logs/covariate_randomise"

running=0
failed=0
pids=()

wait_for_one() {
    local pid
    if ((${#pids[@]} == 0)); then
        return 0
    fi
    pid="${pids[0]}"
    if ! wait "$pid"; then
        failed=$((failed + 1))
    fi
    pids=("${pids[@]:1}")
    running=$((running - 1))
}

while IFS=$'\t' read -r model contrast network mask group_input design_mat design_con output_prefix; do
    if job_complete "$output_prefix"; then
        echo "Already complete: ${output_prefix}" >&2
        continue
    elif [[ -f "${output_prefix}.complete" ]]; then
        echo "Rerunning stale complete marker with missing outputs: ${output_prefix}" >&2
    fi
    mkdir -p "$(dirname "$output_prefix")"
    log_prefix="${fsldir}/logs/covariate_randomise/$(basename "$output_prefix")"
    (
        echo "Starting: ${output_prefix}" >&2
        if [[ "$tfce" == 1 ]]; then
            randomise \
                -i "$group_input" \
                -o "$output_prefix" \
                -m "$mask" \
                -d "$design_mat" \
                -t "$design_con" \
                -n "$nperm" -T -c "$cluster_threshold"
        else
            randomise \
                -i "$group_input" \
                -o "$output_prefix" \
                -m "$mask" \
                -d "$design_mat" \
                -t "$design_con" \
                -n "$nperm" -c "$cluster_threshold"
        fi
        if ! expected_outputs_exist "$output_prefix"; then
            echo "ERROR: randomise finished but expected outputs are missing for ${output_prefix}" >&2
            exit 1
        fi
        date -u +%Y-%m-%dT%H:%M:%SZ >"${output_prefix}.complete"
    ) >"${log_prefix}.stdout.log" 2>"${log_prefix}.stderr.log" &
    pids+=("$!")
    running=$((running + 1))
    if ((running >= maxjobs)); then
        wait_for_one
    fi
done <"$plan"

while ((running > 0)); do
    wait_for_one
done

if [[ "$failed" -gt 0 ]]; then
    echo "ERROR: ${failed} covariate randomise job(s) failed. Check ${fsldir}/logs/covariate_randomise." >&2
    exit 1
fi

echo "Covariate randomise jobs complete." >&2
